### ISSUE TITLE
won't compile in LaTeX

### ISSUE THREAD

**Issue by sanjeevverma1** [raphink/coloredlettrine#2]
downloaded zip file, unpacked. downloaded eb garamond, added to font book and folder with colored lettrine files. attempted to typeset the tex file using XeLaTeX, but persistent error: coloredlettrine.sty cannot be found 

do you have any suggestions on how to make this work? I would really like to use this!!

THANKS!!!!

**Comment by raphink** [comment]
Is the sty file present in your local directory?
